class ConfigData:
    OPEN_AI_KEY = "sk-XXXX"
    MONGO_DB_URI = "mongodb://localhost:27017/"
    DB_NAME = "db_trial"
    COLLECTION_NAME = "db_trial_cl"
    TABLE_SCHEMA = '''
                    "_id": "string",
                    "name": "string",
                    "industry": "string",
                    "founded_year": "string",
                    "employees": "string",
                    "hq_location": "string",
                    "products": "array of strings",
                    "revenue": "string",
                    "ceo": 
                        "name": "string",
                        "age": "string",
                        "email": "string"
                    ,
                    "departments": [
                        "name": "string",
                        "employees": "string",
                        "manager": 
                            "name": "string",
                            "email": "string"
                    ]
                    '''
    
    SCHEMA_DESCRIPTION = '''

                    Here is the description to determine what each key represents:
                    1. _id:
                        - Description: Unique identifier for the document.
                    2. name:
                        - Description: Name of the company.
                    3. industry:
                        - Description: Industry in which the company operates.
                    4. founded_year:
                        - Description: Year in which the company was founded.
                    5. employees:
                        - Description: Total number of employees.
                    6. hq_location:
                        - Description: Headquarters location of the company.
                    7. products:
                        - Description: List of products offered by the company.
                        - Data Type: Array of strings
                    8. revenue:
                        - Description: Revenue generated by the company (in a specific currency).
                    9. ceo:
                        - Description: Information about the CEO.
                        - Fields:
                        - name:
                            - Description: Name of the CEO.
                        - age:
                            - Description: Age of the CEO.
                        - email:
                            - Description: Email address of the CEO.
                    10. departments:
                        - Description: Information about various departments within the company.
                        - Data Type: Array of Embedded Documents
                        - Fields:
                        - name:
                            - Description: Name of the department.
                        - employees:
                            - Description: Total number of employees in the department.
                        - manager:
                            - Description: Information about the department manager.
                            - Fields:
                            - name:
                                - Description: Name of the department manager.
                            - email:
                                - Description: Email address of the department manager.

                    '''
    FEW_SHOT_EXAMPLE_1 = [
                            {
                                "$match": {"departments.employees": {"$gt": 1000}}
                            },
                            {
                                "$project": {
                                    "departments": {
                                        "$filter": {
                                            "input": "$departments",
                                            "as": "dept",
                                            "cond": {"$gt": ["$$dept.employees", 1000]}
                                        }
                                    }
                                }
                            }
                        ]